[workspace]
members = ["cowapi", "cowbin"] 
default-members = ["cowbin"]
resolver = "2"
[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["yum <yumzi114@gmail.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
